const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const TASKS=[
 {id:'bill',icon:'$',name:'Pay the Electric Bill',dept:'ACCOUNTS PAYABLE',desc:'Submit payment before the suspiciously imminent deadline.',level:1,xp:70,diff:'Routine',kind:'bill'},
 {id:'email',icon:'@',name:'Respond to an Email',dept:'CORPORATE COMMUNICATIONS',desc:'Draft a professional reply without using the forbidden word.',level:1,xp:55,diff:'Routine',kind:'email'},
 {id:'paper',icon:'▤',name:'Sort the Paperwork',dept:'RECORDS & COMPLIANCE',desc:'File every document into its obviously correct category.',level:1,xp:65,diff:'Tedious',kind:'paper'},
 {id:'password',icon:'●',name:'Find the Correct Password',dept:'INFORMATION SECURITY',desc:'One of these almost-identical passwords was updated Tuesday.',level:1,xp:60,diff:'Annoying',kind:'password'},
 {id:'captcha',icon:'⌁',name:'Prove You Are Human',dept:'AUTOMATED TRUST',desc:'Complete a perfectly normal and reasonable CAPTCHA.',level:2,xp:85,diff:'Hostile',kind:'captcha'},
 {id:'printer',icon:'▣',name:'Fix the Printer',dept:'DEVICE RELATIONS',desc:'Diagnose an appliance that has chosen violence.',level:2,xp:90,diff:'Hostile',kind:'printer'},
 {id:'code',icon:'#',name:'Enter Verification Code',dept:'IDENTITY ASSURANCE',desc:'Enter the 18-digit code before it expires.',level:3,xp:100,diff:'Cruel',kind:'code'},
 {id:'cables',icon:'≈',name:'Organize the Cables',dept:'FACILITIES',desc:'Connect each cable without crossing the invisible policy line.',level:3,xp:105,diff:'Cruel',kind:'cables'},
 {id:'groceries',icon:'▱',name:'Pack the Groceries',dept:'DOMESTIC LOGISTICS',desc:'Bag everything. Bread goes on the bottom, apparently.',level:4,xp:120,diff:'Malicious',kind:'groceries'},
 {id:'taxes',icon:'%',name:'File Your Taxes',dept:'REVENUE COMPLIANCE',desc:'Complete Form 1040-NOPE without a single clerical error.',level:4,xp:140,diff:'Malicious',kind:'taxes'},
 {id:'furniture',icon:'⌂',name:'Assemble the Furniture',dept:'FLAT-PACK OPERATIONS',desc:'Follow missing instructions using one tiny hex key.',level:5,xp:160,diff:'Inhumane',kind:'furniture'},
 {id:'headphones',icon:'Ω',name:'Untangle Headphones',dept:'PERSONAL EFFECTS',desc:'Locate the six knots that formed while nobody was looking.',level:5,xp:150,diff:'Inhumane',kind:'headphones'}
];
const ACH=[['first','Clocked In','Complete your first task.','✓'],['five','Functioning Adult','Complete 5 tasks.','5'],['ten','Deeply Employable','Complete 10 tasks.','10'],['fast','Under Pressure','Finish with under 10 seconds left.','◷'],['rage','Persistent Asset','Fail or restart 5 times.','↻'],['captcha','Definitely Human','Defeat the impossible CAPTCHA.','⌁'],['printer','IT Department','Fix the printer without percussive maintenance.','▣'],['level3','Middle Management','Reach level 3.','▲'],['level5','Executive Material','Reach level 5.','◆'],['daily','Model Employee','Complete a daily challenge.','★'],['fees','Fee Survivor','Pay a bill despite the surprise fee.','$'],['all','Inbox Zero-ish','Complete every unique task.','∞']];
const base={xp:0,completed:0,completedIds:[],streak:0,bestStreak:0,attempts:0,failures:0,clicks:0,time:0,achievements:[],daily:0,dailyDate:'',sound:true};
let state={...base}, current=null, timer=null, seconds=0, startedAt=0;
try{state={...base,...JSON.parse(localStorage.getItem('taskSimulator')||'{}')}}catch(e){}
const level=()=>Math.min(6,Math.floor(state.xp/100)+1), title=()=>['INTERN','ASSOCIATE','COORDINATOR','SPECIALIST','MANAGER','DIRECTOR'][level()-1];
function save(){localStorage.setItem('taskSimulator',JSON.stringify(state));$('#saveStatus').textContent='Autosaved just now'}
function beep(type='click'){if(!state.sound)return;const a=new (window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=type==='win'?660:type==='bad'?150:320;g.gain.setValueAtTime(.055,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+(type==='win'?.35:.08));o.start();o.stop(a.currentTime+(type==='win'?.35:.08))}
function toast(title,msg){const n=document.createElement('div');n.className='toast';n.innerHTML=`<b>${title}</b>${msg}`;$('#toasts').append(n);setTimeout(()=>n.remove(),3500)}
function unlock(id){if(!state.achievements.includes(id)){state.achievements.push(id);const a=ACH.find(x=>x[0]===id);toast('ACHIEVEMENT UNLOCKED',a[1]);beep('win')}}
function checkAchievements(){if(state.completed>=1)unlock('first');if(state.completed>=5)unlock('five');if(state.completed>=10)unlock('ten');if(state.failures>=5)unlock('rage');if(level()>=3)unlock('level3');if(level()>=5)unlock('level5');if(TASKS.every(t=>state.completedIds.includes(t.id)))unlock('all')}
function dailyCheck(){const d=new Date().toDateString();if(state.dailyDate!==d){state.dailyDate=d;state.daily=0;save()}if(state.daily>=3&&!state.achievements.includes('daily')){state.xp+=150;unlock('daily');toast('DAILY COMPLETE','Your reward is additional responsibility.')}}
function render(){checkAchievements();dailyCheck();const l=level(),within=state.xp%100;$('#levelLabel').textContent=`LEVEL ${l} · ${title()}`;$('#xpFill').style.width=within+'%';$('#xpText').textContent=`${within} / 100 XP`;$('#score').textContent=(state.xp*13+state.completed*47).toLocaleString();$('#completedMetric').textContent=state.completed;$('#streakMetric').textContent=state.streak;$('#timeMetric').textContent=Math.floor(state.time/60)+'m';$('#achievementMetric').textContent=`${state.achievements.length} / ${ACH.length}`;$('#dailyFill').style.width=Math.min(100,state.daily/3*100)+'%';$('#dailyText').textContent=`${Math.min(3,state.daily)} / 3 completed`;$('#queueCount').textContent=TASKS.filter(t=>t.level<=l).length;$('#soundBtn').textContent=state.sound?'♫':'×';
 const avail=TASKS.filter(t=>t.level<=l);$('#dashboardTasks').innerHTML=avail.slice(0,4).map(rowHTML).join('');renderTasks();renderAchievements();renderStats();bindStarts();save()}
function rowHTML(t){return `<div class="task-row"><span class="task-symbol">${t.icon}</span><div class="task-info"><b>${t.name}</b><span>${t.dept} · <span class="difficulty">${t.diff}</span></span></div><button class="start-btn" data-task="${t.id}">${state.completedIds.includes(t.id)?'Again':'Begin'}</button></div>`}
function renderTasks(filter='all'){const l=level();$('#allTasks').innerHTML=TASKS.filter(t=>filter==='all'||(filter==='available')===(t.level<=l)).map(t=>`<article class="task-card ${t.level>l?'locked':''}"><span class="task-symbol">${t.level>l?'▥':t.icon}</span><h3>${t.name}</h3><p>${t.desc}</p><footer><span class="difficulty">${t.level>l?'UNLOCKS LEVEL '+t.level:t.diff+' · +'+t.xp+' XP'}</span>${t.level>l?'':`<button class="start-btn" data-task="${t.id}">${state.completedIds.includes(t.id)?'Repeat':'Begin'}</button>`}</footer></article>`).join('');bindStarts()}
function renderAchievements(){$('#achievementGrid').innerHTML=ACH.map(a=>`<article class="achievement ${state.achievements.includes(a[0])?'unlocked':''}"><span class="badge">${state.achievements.includes(a[0])?a[3]:'?'}</span><div><h3>${a[1]}</h3><p>${a[2]}</p></div></article>`).join('')}
function renderStats(){const stats=[['TOTAL CLICKS',state.clicks],['FAILED ATTEMPTS',state.failures],['BEST STREAK',state.bestStreak],['XP EARNED',state.xp],['TASKS ATTEMPTED',state.attempts],['TIME SPENT',Math.floor(state.time/60)+'m '+state.time%60+'s']];$('#statsGrid').innerHTML=stats.map(s=>`<article class="stat-card"><span>${s[0]}</span><b>${s[1]}</b></article>`).join('')}
function bindStarts(){$$('[data-task]').forEach(b=>b.onclick=()=>startTask(b.dataset.task))}
function stage(html,brief,time=75){$('#taskStage').innerHTML=html;$('#taskBrief').textContent=brief;seconds=time;updateTimer()}
function startClock(){clearInterval(timer);timer=setInterval(()=>{seconds--;if(seconds<=0)fail('Deadline exceeded. The deadline has filed a complaint.');updateTimer()},1000)}
function startTask(id){current=TASKS.find(t=>t.id===id);state.attempts++;startedAt=Date.now();$('#modalTitle').textContent=current.name;$('#modalDept').textContent=current.dept;$('#attemptText').textContent=`Attempt ${state.attempts} · Please remain calm`;$('#modal').classList.add('open');buildTask(current.kind);startClock();beep()}
function updateTimer(){$('#modalTimer').textContent=`◷ ${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(Math.max(0,seconds%60)).padStart(2,'0')}`}
function fail(msg){clearInterval(timer);state.failures++;state.streak=0;beep('bad');toast('TASK FAILED',msg);save();setTimeout(()=>{if(current){buildTask(current.kind);startClock()}},500);checkAchievements()}
function win(extra='Your compliance has been recorded.'){clearInterval(timer);const first=!state.completedIds.includes(current.id);state.xp+=current.xp;state.completed++;state.daily++;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak);if(first)state.completedIds.push(current.id);if(seconds<10)unlock('fast');if(current.id==='captcha')unlock('captcha');if(current.id==='printer')unlock('printer');$('#taskStage').innerHTML=`<div class="success"><div class="check">✓</div><h2>Task completed.</h2><p>${extra}</p><button class="primary" id="returnDesk">Return to desk</button></div>`;$('#returnDesk').onclick=closeTask;$('#taskBrief').textContent=`+${current.xp} XP · Performance noted with restrained approval.`;beep('win');save();render()}
function closeTask(){clearInterval(timer);if(current&&startedAt)state.time+=Math.floor((Date.now()-startedAt)/1000);current=null;startedAt=0;$('#modal').classList.remove('open');save();render()}
function buildTask(k){if(k==='bill')bill();else if(k==='email')email();else if(k==='paper')paper();else if(k==='password')password();else if(k==='captcha')captcha();else if(k==='printer')printer();else if(k==='code')code();else generic(k)}
function bill(){stage(`<div class="form-grid"><div class="field"><label>ACCOUNT NUMBER</label><input id="acct" placeholder="Try 004-819-22"></div><div class="field"><label>PAYMENT AMOUNT</label><input id="amount" value="$84.17"></div><div class="field full"><label>PAYMENT METHOD</label><select><option>Checking ending in 0912</option></select></div><div class="field full"><div class="fee-line"><span>Electric service</span><b>$84.17</b></div><div class="fee-line surprise"><span>Convenience inconvenience fee</span><b>$6.99</b></div></div><div class="field full"><label><input type="checkbox" id="fee"> I enthusiastically accept the surprise fee</label></div><button class="primary" id="pay">Submit Payment</button></div>`,`Payment is due in 01:15. Account number appears somewhere in this sentence: 004-819-22.`,75);$('#pay').onclick=()=>{if($('#acct').value.trim()!=='004-819-22'||!$('#fee').checked)return fail('One field was wrong. For security, everything has reset.');unlock('fees');win('Payment accepted. A receipt will arrive in 6–18 months.')}}
function email(){stage(`<div class="field"><label>TO</label><input value="Everyone, including the CEO" disabled></div><div class="field" style="margin-top:12px"><label>REPLY (exactly 42–120 characters; do not use “sorry”)</label><input id="subject" placeholder="Subject (must include: Update)"><textarea id="reply" style="width:100%;height:120px;margin-top:8px;border:1px solid #cfd9dd;padding:10px" placeholder="Compose a warm but legally neutral response..."></textarea><small id="count">0 characters</small></div><button class="primary" id="send" style="margin-top:12px">Reply All</button>`,`Reply professionally. Include “received” and “Tuesday”. The word “sorry” triggers compliance review.`,70);$('#reply').oninput=e=>$('#count').textContent=e.target.value.length+' characters';$('#send').onclick=()=>{const v=$('#reply').value,s=$('#subject').value;if(!s.includes('Update')||v.length<42||v.length>120||!/received/i.test(v)||!/Tuesday/i.test(v)||/sorry/i.test(v))return fail('Tone analysis rejected the message. Draft discarded for your convenience.');win('Email sent to 4,813 recipients. Reply-all storm pending.')}}
function paper(){const docs=[['Invoice','finance'],['Receipt','finance'],['Memo','internal'],['Policy','internal'],['Coupon','trash'],['Draft','trash']].sort(()=>Math.random()-.5);stage(`<p style="font-size:10px;color:#71808c">Click a document, then its destination. Sorting rules are classified.</p><div class="paper-stack">${docs.map((d,i)=>`<div class="paper" data-type="${d[1]}">FORM ${String(i+17).padStart(3,'0')}<br><b>${d[0]}</b><br>Retention: maybe</div>`).join('')}</div><div class="bins"><div class="bin" data-bin="finance">FINANCIAL</div><div class="bin" data-bin="internal">INTERNAL</div><div class="bin" data-bin="trash">SHREDDER</div></div>`,`Sort all six documents. One incorrect filing restarts the entire batch.`,80);let sel=null,count=0;$$('.paper').forEach(p=>p.onclick=()=>{sel=p;p.style.outline='2px solid #e98535'});$$('.bin').forEach(b=>b.onclick=()=>{if(!sel)return;if(sel.dataset.type!==b.dataset.bin)return fail('Misfile detected. Records has returned the entire batch.');sel.remove();sel=null;if(++count===6)win('All records filed. They will now never be seen again.')})}
function password(){const correct='P@ssw0rd!_Final_FINAL2';let arr=['P@ssw0rd!_Final_FINAL','P@ssw0rd!_Final_FINAL1','P@ssword!_Final_FINAL2','P@ssw0rd1_Final_FINAL2',correct,'P@ssw0rd!_Final_FlNAL2','P@ssw0rd!_final_FINAL2'].sort(()=>Math.random()-.5);stage(`<p style="font-size:10px">Security hint: “The final final one, with a 2, not the one with a one.”</p><div class="password-list">${arr.map(p=>`<button>${p}</button>`).join('')}</div><div class="field"><label>SELECTED PASSWORD</label><input id="chosen" readonly></div><button class="primary" id="login" style="margin-top:12px">Sign In</button>`,`You have three theoretical attempts. Passwords may look identical as a security feature.`,60);$$('.password-list button').forEach(b=>b.onclick=()=>$('#chosen').value=b.textContent);$('#login').onclick=()=>$('#chosen').value===correct?win('Access granted. Mandatory password change scheduled tomorrow.'):fail('Incorrect. All passwords have been reshuffled.')}
function captcha(){const code=Math.random().toString(36).slice(2,8).toUpperCase();stage(`<div class="captcha-box"><p>Select the traffic lights. There are no traffic lights.</p><div class="captcha-code">${code}</div><div class="field" style="margin:18px auto;max-width:260px"><input id="cap" autocomplete="off" placeholder="Enter the text instead"></div><label style="font-size:10px"><input type="checkbox" id="robot"> I am not a robot (robots must leave unchecked)</label><br><button class="primary" id="verify" style="margin-top:18px">Verify</button></div>`,`Alternative accessibility instruction: enter the warped code, leave the checkbox unchecked, then click Verify.`,55);$('#verify').onclick=()=>{if($('#cap').value.trim().toUpperCase()!==code||$('#robot').checked)return fail('Humanity score insufficient. A new challenge has been generated.');win('Human status provisionally approved for 24 hours.')}}
function printer(){stage(`<div class="printer"></div><div class="printer-btns"><button class="primary" data-action="power">Power cycle</button><button class="primary" data-action="tray">Open tray</button><button class="primary" data-action="paper">Add paper</button></div><p id="printerLog" style="text-align:center;font:10px monospace;color:#71808c">ERROR 0xPAPER: Paper absent but also jammed.</p>`,`Perform actions in this exact order: open tray, add paper, power cycle. Buttons may migrate when approached.`,70);let seq=[],need=['tray','paper','power'];$$('[data-action]').forEach(b=>{b.onmouseenter=()=>{if(Math.random()<.38){b.style.transform=`translate(${Math.random()*20-10}px,${Math.random()*8-4}px)`}};b.onclick=()=>{seq.push(b.dataset.action);$('#printerLog').textContent='ACTION LOG: '+seq.join(' → ');if(seq.some((x,i)=>x!==need[i]))return fail('Printer is now offended. Diagnostic sequence reset.');if(seq.length===3)win('Printer online. Cyan cartridge immediately low.')}})}
function code(){const c=Array.from({length:18},()=>Math.floor(Math.random()*10)).join('');stage(`<p style="text-align:center;font:12px monospace;letter-spacing:4px;background:#fff;padding:12px" id="shownCode">${c}</p><div class="code-inputs">${[...c].map((_,i)=>`<input maxlength="1" data-i="${i}" inputmode="numeric">`).join('')}</div><button class="primary" id="codeGo" style="display:block;margin:20px auto">Confirm identity</button>`,`Enter all 18 digits. Pasting is forbidden by a committee. Code expires quickly.`,35);const inputs=$$('.code-inputs input');inputs.forEach((n,i)=>n.oninput=()=>{if(n.value&&!/\d/.test(n.value))n.value='';if(n.value&&inputs[i+1])inputs[i+1].focus()});$('#codeGo').onclick=()=>inputs.map(x=>x.value).join('')===c?win('Identity confirmed. Your identity appears disappointed.'):fail('A digit was incorrect. A brand-new code has been issued.');setTimeout(()=>{if(current?.kind==='code'&&Math.random()<.9)randomInterrupt()},9000)}
function generic(k){const configs={cables:['Connect the labeled plugs in order: A, C, B, D.',['A','C','B','D']],groceries:['Pack items from heaviest to lightest: cans, milk, eggs, bread.',['cans','milk','eggs','bread']],taxes:['Enter the sacred sequence: W2, 1099, 1040, regret.',['W2','1099','1040','regret']],furniture:['Assemble in order: dowel, screw, cam, sigh.',['dowel','screw','cam','sigh']],headphones:['Undo knots in order: 3, 1, 4, 2.',['3','1','4','2']]};const [brief,seq]=configs[k];let choices=[...seq].sort(()=>Math.random()-.5),chosen=[];stage(`<p style="font-size:11px;text-align:center">${brief}</p><div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap;margin:40px 0">${choices.map(x=>`<button class="primary choice">${x}</button>`).join('')}</div><p id="sequence" style="text-align:center;color:#71808c;font:11px monospace">SEQUENCE: —</p>`,`${brief} One mistake resets all progress.`,k==='taxes'?45:60);$$('.choice').forEach(b=>b.onclick=()=>{chosen.push(b.textContent);b.disabled=true;b.style.opacity=.35;$('#sequence').textContent='SEQUENCE: '+chosen.join(' → ');if(chosen.some((x,i)=>x!==seq[i]))return fail('Procedure violation. All previous work has been respectfully destroyed.');if(chosen.length===seq.length)win('The procedure succeeded against all reasonable expectations.');});if(['taxes','furniture'].includes(k))setTimeout(()=>current&&randomAd(),4000)}
function randomAd(){const ad=document.createElement('div');ad.className='ad-popup';ad.innerHTML='<button class="x">×</button><span class="eyebrow">IMPORTANT OPPORTUNITY</span><h3>You may already be productive!</h3><p style="font-size:10px">Download twelve toolbars to find out.</p><button class="primary">Remind me constantly</button>';$('#taskStage').append(ad);ad.querySelector('.x').onclick=()=>ad.remove()}
function randomInterrupt(){const n=document.createElement('div');n.className='interrupt';n.style.left=Math.random()*60+15+'%';n.style.top=Math.random()*55+15+'%';n.innerHTML='<span class="eyebrow">CALENDAR REMINDER</span><h3>Meeting: Meeting Planning</h3><p style="font-size:10px">This meeting started 3 minutes ago.</p><button class="primary">Dismiss (politely)</button>';$('#interruptLayer').append(n);n.querySelector('button').onclick=()=>n.remove();setTimeout(()=>n.remove(),8000)}
$$('.nav').forEach(n=>n.onclick=()=>{$$('.nav,.page').forEach(x=>x.classList.remove('active'));n.classList.add('active');$('#'+n.dataset.page+'Page').classList.add('active');beep()});$$('[data-goto]').forEach(b=>b.onclick=()=>$('.nav[data-page="'+b.dataset.goto+'"]').click());$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTasks(b.dataset.filter)});$('#closeModal').onclick=closeTask;$('#giveUp').onclick=()=>{state.failures++;state.streak=0;closeTask()};$('#soundBtn').onclick=()=>{state.sound=!state.sound;render()};$('#resetBtn').onclick=()=>{if(confirm('Delete all productivity records? This cannot be blamed on IT.')){state={...base};save();render()}};document.addEventListener('click',()=>state.clicks++);setInterval(()=>{const msgs=['The printer on Floor 3 is experiencing personal issues.','Reminder: passwords expire every 11 minutes.','Unattended paperwork will be assigned more paperwork.','The break room microwave has been promoted.'];$('#tickerText').textContent=msgs[Math.floor(Date.now()/6000)%msgs.length]},6000);setInterval(()=>{if(current&&level()>=3&&Math.random()<.18)randomInterrupt()},12000);render();
